name: build

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: sssomeshhh
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Build Docker Image
        id: docker_build_push
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          target: llvm-build
          push: true
          tags: |
            ghcr.io/sssomeshhh/llvm-builds:ib-${{ github.sha }}
            ghcr.io/sssomeshhh/llvm-builds:ib-${{ github.ref_name }}
          build-args: |
            BASE_IMAGE_BUILD=ubuntu:jammy
            LLVM_VERSION_TAG=15.0.3
