name: build

on:
  push:
    tags:
      - "*"

jobs:
  base:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build Load Base
        id: build_load_base
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: base.Dockerfile
          target: base
          push: false
          outputs: type=docker,dest=/tmp/iBase.tar
          tags: |
            build:base
          build-args: |
            LLVM_VERSION_TAG=15.0.3
      - name: Upload iBase.tar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: iBase.tar
          path: /tmp/iBase.tar

  setup-00:
    runs-on: ubuntu-22.04
    needs: [base]
    steps:
      - name: Download iBase.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iBase.tar
          path: /tmp/iBase.tar
      - name: Load iBase.tar
        run: |
          docker load --input /tmp/iBase.tar
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build Load Clean
        id: build_load_clean
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: clean.Dockerfile
          target: clean
          push: false
          outputs: type=docker,dest=/tmp/iSetup.tar
          tags: |
            build:setup
          build-args: |
            BASE_IMAGE=build:base
      - name: Upload iSetup.tar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: iSetup.tar
          path: /tmp/iSetup.tar

  chain-00:
    runs-on: ubuntu-22.04
    needs: [setup-00]
    steps:
      - name: Download iSetup.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iSetup.tar
          path: /tmp/iSetup.tar
      - name: Load iSetup.tar
        run: |
          docker load --input /tmp/iSetup.tar
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build Load Chain
        id: build_load_chain
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: chain.Dockerfile
          target: chain
          push: false
          outputs: type=docker,dest=/tmp/iChain.tar
          tags: |
            build:chain
          build-args: |
            SETUP_IMAGE=build:setup
      - name: Upload iChain.tar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: iChain.tar
          path: /tmp/iChain.tar

  setup-01:
    runs-on: ubuntu-22.04
    needs: [chain-00]
    steps:
      - name: Download iBase.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iBase.tar
          path: /tmp/iBase.tar
      - name: Load iBase.tar
        run: |
          docker load --input /tmp/iBase.tar
      - name: Download iChain.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iChain.tar
          path: /tmp/iChain.tar
      - name: Load iChain.tar
        run: |
          docker load --input /tmp/iChain.tar
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build Load Stage
        id: build_load_stage
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: stage.Dockerfile
          target: stage
          push: false
          outputs: type=docker,dest=/tmp/iSetup.tar
          tags: |
            build:setup
          build-args: |
            BASE_IMAGE=build:base
            CHAIN_IMAGE=build:chain
      - name: Upload iSetup.tar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: iSetup.tar
          path: /tmp/iSetup.tar

  chain-01:
    runs-on: ubuntu-22.04
    needs: [setup-01]
    steps:
      - name: Download iSetup.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iSetup.tar
          path: /tmp/iSetup.tar
      - name: Load iSetup.tar
        run: |
          docker load --input /tmp/iSetup.tar
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build Load Chain
        id: build_load_chain
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: chain.Dockerfile
          target: chain
          push: false
          outputs: type=docker,dest=/tmp/iChain.tar
          tags: |
            build:chain
          build-args: |
            SETUP_IMAGE=build:setup
      - name: Upload iChain.tar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: iChain.tar
          path: /tmp/iChain.tar

  setup-02:
    runs-on: ubuntu-22.04
    needs: [chain-01]
    steps:
      - name: Download iBase.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iBase.tar
          path: /tmp/iBase.tar
      - name: Load iBase.tar
        run: |
          docker load --input /tmp/iBase.tar
      - name: Download iChain.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iChain.tar
          path: /tmp/iChain.tar
      - name: Load iChain.tar
        run: |
          docker load --input /tmp/iChain.tar
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build Load Stage
        id: build_load_stage
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: stage.Dockerfile
          target: stage
          push: false
          outputs: type=docker,dest=/tmp/iSetup.tar
          tags: |
            build:setup
          build-args: |
            BASE_IMAGE=build:base
            CHAIN_IMAGE=build:chain
      - name: Upload iSetup.tar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: iSetup.tar
          path: /tmp/iSetup.tar

  chain-02:
    runs-on: ubuntu-22.04
    needs: [setup-02]
    steps:
      - name: Download iSetup.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iSetup.tar
          path: /tmp/iSetup.tar
      - name: Load iSetup.tar
        run: |
          docker load --input /tmp/iSetup.tar
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build Load Chain
        id: build_load_chain
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: chain.Dockerfile
          target: chain
          push: false
          outputs: type=docker,dest=/tmp/iChain.tar
          tags: |
            build:chain
          build-args: |
            SETUP_IMAGE=build:setup
      - name: Upload iChain.tar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: iChain.tar
          path: /tmp/iChain.tar

  setup-03:
    runs-on: ubuntu-22.04
    needs: [chain-02]
    steps:
      - name: Download iBase.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iBase.tar
          path: /tmp/iBase.tar
      - name: Load iBase.tar
        run: |
          docker load --input /tmp/iBase.tar
      - name: Download iChain.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iChain.tar
          path: /tmp/iChain.tar
      - name: Load iChain.tar
        run: |
          docker load --input /tmp/iChain.tar
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build Load Stage
        id: build_load_stage
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: stage.Dockerfile
          target: stage
          push: false
          outputs: type=docker,dest=/tmp/iSetup.tar
          tags: |
            build:setup
          build-args: |
            BASE_IMAGE=build:base
            CHAIN_IMAGE=build:chain
      - name: Upload iSetup.tar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: iSetup.tar
          path: /tmp/iSetup.tar

  chain-03:
    runs-on: ubuntu-22.04
    needs: [setup-03]
    steps:
      - name: Download iSetup.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iSetup.tar
          path: /tmp/iSetup.tar
      - name: Load iSetup.tar
        run: |
          docker load --input /tmp/iSetup.tar
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build Load Chain
        id: build_load_chain
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: chain.Dockerfile
          target: chain
          push: false
          outputs: type=docker,dest=/tmp/iChain.tar
          tags: |
            build:chain
          build-args: |
            SETUP_IMAGE=build:setup
      - name: Upload iChain.tar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: iChain.tar
          path: /tmp/iChain.tar

  setup-04:
    runs-on: ubuntu-22.04
    needs: [chain-03]
    steps:
      - name: Download iBase.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iBase.tar
          path: /tmp/iBase.tar
      - name: Load iBase.tar
        run: |
          docker load --input /tmp/iBase.tar
      - name: Download iChain.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iChain.tar
          path: /tmp/iChain.tar
      - name: Load iChain.tar
        run: |
          docker load --input /tmp/iChain.tar
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build Load Stage
        id: build_load_stage
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: stage.Dockerfile
          target: stage
          push: false
          outputs: type=docker,dest=/tmp/iSetup.tar
          tags: |
            build:setup
          build-args: |
            BASE_IMAGE=build:base
            CHAIN_IMAGE=build:chain
      - name: Upload iSetup.tar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: iSetup.tar
          path: /tmp/iSetup.tar

  chain-04:
    runs-on: ubuntu-22.04
    needs: [setup-04]
    steps:
      - name: Download iSetup.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iSetup.tar
          path: /tmp/iSetup.tar
      - name: Load iSetup.tar
        run: |
          docker load --input /tmp/iSetup.tar
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build Load Chain
        id: build_load_chain
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: chain.Dockerfile
          target: chain
          push: false
          outputs: type=docker,dest=/tmp/iChain.tar
          tags: |
            build:chain
          build-args: |
            SETUP_IMAGE=build:setup
      - name: Upload iChain.tar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: iChain.tar
          path: /tmp/iChain.tar

  end:
    runs-on: ubuntu-22.04
    needs: [chain-04]
    steps:
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build Load End
        id: build_load_end
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: end.Dockerfile
          target: end
          push: false
          outputs: type=docker,dest=/tmp/iEnd.tar
          tags: |
            build:end
          build-args: |
            CHAIN_IMAGE=build:chain
      - name: Upload iEnd.tar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: iEnd.tar
          path: /tmp/iEnd.tar

  push:
    runs-on: ubuntu-22.04
    needs: [end]
    steps:
      - name: Download iEnd.tar
        uses: actions/download-artifact@v3.0.1
        with:
          name: iEnd.tar
          path: /tmp/iEnd.tar
      - name: Load iEnd.tar
        run: |
          docker load --input /tmp/iEnd.tar
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: sssomeshhh
          password: ${{ secrets.GH_PACKAGES_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build Docker Image
        id: docker_build_push
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: release.Dockerfile
          target: llvm-release
          push: true
          tags: |
            ghcr.io/sssomeshhh/llvm-builds:${{ github.sha }}
            ghcr.io/sssomeshhh/llvm-builds:${{ github.ref_name }}
          build-args: |
            END_IMAGE=build:end

  release:
    runs-on: ubuntu-latest
    needs: [push]
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  pack-bd:
    runs-on: ubuntu-22.04
    needs: [release]
    steps:
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Load Pack BD
        id: load_pack_bd
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: pack.Dockerfile
          target: pack
          push: false
          tags: |
            pack:bd
          build-args: |
            END_IMAGE=build:end
            X=b
            R=/root/llvm
      - name: Copy BD
        id: copy_bd
        run: |
          docker run --rm --tty --detach --interactive --name=cntnr-bd pack:bd bash;
          docker cp cntnr-bd:/root/llvm/bt.xz ./;
          docker stop cntnr-bd;
      - name: Upload
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bt.xz

  pack-id:
    runs-on: ubuntu-22.04
    needs: [release]
    steps:
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Load Pack ID
        id: load_pack_id
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: pack.Dockerfile
          target: pack
          push: false
          tags: |
            pack:id
          build-args: |
            END_IMAGE=build:end
            X=i
            R=/root/llvm
      - name: Copy ID
        id: copy_id
        run: |
          docker run --rm --tty --detach --interactive --name=cntnr-id pack:id bash;
          docker cp cntnr-id:/root/llvm/it.xz ./;
          docker stop cntnr-id;
      - name: Upload
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            it.xz

  pack-sd:
    runs-on: ubuntu-22.04
    needs: [release]
    steps:
      - name: Setup Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Load Pack SD
        id: load_pack_sd
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          file: pack.Dockerfile
          target: pack
          push: false
          tags: |
            pack:sd
          build-args: |
            END_IMAGE=build:end
            X=s
            R=/root/llvm
      - name: Copy SD
        id: copy_sd
        run: |
          docker run --rm --tty --detach --interactive --name=cntnr-sd pack:sd bash;
          docker cp cntnr-sd:/root/llvm/st.xz ./;
          docker stop cntnr-sd;
      - name: Upload
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            st.xz
