name: release

on:
  push: [tags]

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create
        id: create
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  pack-bd:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v3
      - name: Pack BD
        id: pack_bd
        env:
          IMG_TAG: ghcr.io/sssomeshhh/llvm-builds:test-8e9436e8385e13335569270492586a43121344f2
        run: |
          export DOCKER_BUILDKIT=1;
          ./dckr.sh b /root/llvm $IMG_TAG;
      - name: Upload
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bt.xz

  pack-id:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v3
      - name: Pack ID
        id: pack_id
        env:
          IMG_TAG: ghcr.io/sssomeshhh/llvm-builds:test-8e9436e8385e13335569270492586a43121344f2
        run: |
          export DOCKER_BUILDKIT=1;
          ./dckr.sh i /root/llvm $IMG_TAG;
      - name: Upload
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            it.xz

  pack-sd:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v3
      - name: Pack SD
        id: pack_sd
        env:
          IMG_TAG: ghcr.io/sssomeshhh/llvm-builds:test-8e9436e8385e13335569270492586a43121344f2
        run: |
          export DOCKER_BUILDKIT=1;
          ./dckr.sh s /root/llvm $IMG_TAG;
      - name: Upload
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            st.xz
